{% set name = "nomic" %}
{% set version = "3.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nomic-{{ version }}.tar.gz
  sha256: d74df6cc2fcb85f9365c9af44782ef278c8ba243701a72804490ae184a405714

build:
  entry_points:
    - nomic=nomic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - jsonlines
    - loguru
    - rich
    - requests
    - numpy
    - pandas
    - pydantic
    - tqdm
    - pyarrow
    - pillow
    - pyjwt

test:
  imports:
    - nomic
  commands:
    - pip check
    - nomic --help
  requires:
    - pip

about:
  home: https://github.com/nomic-ai/nomic
  summary: The official Nomic python client.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
