{% set name = "nomic" %}
{% set version = "3.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomic-{{ version }}.tar.gz
  sha256: 0f660d6b53676a9c7bb3969f70075358a00c612443cd599d26d13b20577aa5e6

build:
  entry_points:
    - nomic=nomic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - jsonlines
    - loguru
    - rich
    - requests
    - numpy
    - pandas
    - pydantic
    - tqdm
    - pyarrow
    - pillow
    - pyjwt

test:
  imports:
    - nomic
  commands:
    - pip check
    - nomic --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nomic-ai/nomic
  summary: The official Nomic python client.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
