{% set name = "nomic" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomic-{{ version }}.tar.gz
  sha256: 97bef089e54adf21901cf1dcf87dd21e8e88aaebf365903e93cbf57fdd6d65f4

build:
  entry_points:
    - nomic=nomic.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - jsonschema >=4.23.0,<5
    - python >={{ python_min }}
    - click
    - jsonlines
    - loguru
    - rich
    - requests
    - numpy
    - pandas
    - pydantic >=2,<3
    - tqdm
    - pyarrow
    - pillow
    - pyjwt

test:
  imports:
    - nomic
  commands:
    - pip check
    - nomic --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nomic-ai/nomic
  summary: The official Nomic python client.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
